local DIR = debug.getinfo(1, "S").source:sub(2):match("(.*[/\\])") or "./"
local Board = assert(loadfile(DIR .. "board.lua"))()

local function guess(board, word)
    board.current = {}
    for i = 1, #word do board:typeLetter(word:sub(i, i)) end
    return board:submit()
end

describe("Dated puzzles", function()
    it("restores each date's unfinished row and accepted guesses after reopening", function()
        local board = Board:new()
        board:selectDate("2024-01-01", "APPLE")
        assert.are.equal("ok", guess(board, "STARE"))
        board:typeLetter("P")
        board:selectDate("2024-01-02", "ABOUT")
        board:typeLetter("A")

        local reopened = Board:new()
        reopened:load(board:serialize())
        assert.is_true(reopened:selectDate("2024-01-01"))
        assert.are.equal("APPLE", reopened.secret)
        assert.are.same({ "P" }, reopened.current)
        assert.are.equal(1, #reopened.guesses)
        assert.is_true(reopened:selectDate("2024-01-02"))
        assert.are.same({ "A" }, reopened.current)
    end)

    it("keeps counters current and never counts restored outcomes twice", function()
        local board = Board:new()
        board:selectDate("2024-01-01", "APPLE")
        assert.are.equal("win", guess(board, "APPLE"))
        board:selectDate("2024-01-02", "ABOUT")
        for _ = 1, 6 do guess(board, "STARE") end
        assert.is_true(board.lost)
        assert.are.equal(1, board.losses)
        board:selectDate("2024-01-01")
        assert.are.equal("done", guess(board, "APPLE"))
        assert.are.equal(1, board.wins)
        assert.are.equal(1, board.losses)
        assert.are.equal(0, board.streak)
    end)

    it("always accepts an API answer missing from the bundled dictionary", function()
        local board = Board:new()
        board:selectDate("2024-01-01", "QZXJK")
        assert.are.equal("win", guess(board, "QZXJK"))
    end)

    it("preserves dated games while playing offline and French games", function()
        local board = Board:new()
        board:selectDate("2024-01-01", "APPLE")
        board:typeLetter("A")
        board:randomGame("fr")
        assert.is_nil(board.puzzle_date)
        assert.are.equal("fr", board.lang)
        board:selectDate("2024-01-01")
        assert.are.equal("en", board.lang)
        assert.are.same({ "A" }, board.current)
    end)

    it("loads legacy saves and preserves their statistics", function()
        local board = Board:new()
        board:load({ secret = "APPLE", wins = 3, losses = 2, streak = 1 })
        assert.are.equal("APPLE", board.secret)
        assert.is_false(board:selectDate("2024-01-01"))
        board:selectDate("2024-01-01", "ABOUT")
        assert.are.equal(3, board.wins)
        assert.are.equal(2, board.losses)
    end)

    it("serializes date history without recursive references", function()
        local board = Board:new()
        board:selectDate("2024-01-01", "APPLE")
        board:selectDate("2024-01-02", "ABOUT")
        local state = board:serialize()
        for _, saved in pairs(state.dated_games) do assert.is_nil(saved.dated_games) end
        local json = require("dkjson")
        local reopened = Board:new()
        assert.is_true(reopened:load(json.decode(json.encode(state))))
        reopened:selectDate("2024-01-01")
        assert.are.equal("APPLE", reopened.secret)
    end)
end)
